name: Publish on PyPI

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install development tools
        run: sudo apt update && apt install git python3 python3-pip
      - name: update pip to latest version, install twine and setuptools
        run: pip3 install --upgrade pip twine setuptools
      - uses: actions/checkout@v2
      - name: install dependencies
        run: pip3 install -r requirements.txt
      - name: build source distribution
        run: python3 setup.py sdist
        
      
